services:
  db:
    image: postgres:16-alpine
    container_name: bcb-db
    restart: always
    environment:
      POSTGRES_DB: bcb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: