CREATE TABLE tb_clients (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(150)   NOT NULL,
    document      VARCHAR(20)    NOT NULL,
    document_type VARCHAR(255)   NOT NULL,
    plan_type     VARCHAR(255)   NOT NULL,
    balance       NUMERIC(38, 2) NOT NULL,
    client_limit  NUMERIC(38, 2) NOT NULL,
    active        BOOLEAN        NOT NULL,
    created_at    TIMESTAMP(6)   NOT NULL,
    updated_at    TIMESTAMP(6)   NOT NULL,
    CONSTRAINT uk_clients_document UNIQUE (document),
    CONSTRAINT ck_clients_document_type CHECK (document_type IN ('CPF', 'CNPJ')),
    CONSTRAINT ck_clients_plan_type CHECK (plan_type IN ('PRE_PAID', 'POST_PAID'))
);

CREATE TABLE tb_conversations (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id            BIGINT       NOT NULL,
    recipient_id         INTEGER      NOT NULL,
    recipient_name       VARCHAR(255) NOT NULL,
    last_message_content VARCHAR(255) NOT NULL,
    last_message_time    TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    unread_count         INTEGER      NOT NULL,
    CONSTRAINT fk_conversations_client FOREIGN KEY (client_id) REFERENCES tb_clients (id)
);

CREATE TABLE tb_messages (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT         NOT NULL,
    sender_id       BIGINT         NOT NULL,
    recipient_id    INTEGER,
    content         VARCHAR(255)   NOT NULL,
    created_at      TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    priority        VARCHAR(255)   NOT NULL,
    status          VARCHAR(255)   NOT NULL,
    cost            NUMERIC(38, 2) NOT NULL,
    CONSTRAINT fk_messages_conversation FOREIGN KEY (conversation_id) REFERENCES tb_conversations (id),
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES tb_clients (id),
    CONSTRAINT ck_messages_priority CHECK (priority IN ('NORMAL', 'URGENT')),
    CONSTRAINT ck_messages_status CHECK (status IN ('QUEUED', 'PROCESSING', 'SENT', 'DELIVERED', 'READ', 'FAILED'))
);
